<?php
include 'anls_db.php';
session_start();
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Analytics | Remindo</title>
    <link rel="stylesheet" href="anstyl/anlsr.css">
</head>
<body>
    <?php 
    if(isset($_POST['pd'])){
        function getIPAddress() {
             if(!empty($_SERVER['HTTP_CLIENT_IP'])) {  
                        $ip = $_SERVER['HTTP_CLIENT_IP'];  
                }  
            elseif (!empty($_SERVER['HTTP_X_FORWARDED_FOR'])) {  
                        $ip = $_SERVER['HTTP_X_FORWARDED_FOR'];  
             } 
            else{  
                     $ip = $_SERVER['REMOTE_ADDR'];  
             }  
             return $ip;  
        }if($_POST['pd']=="SambarTalk"){$_SESSION['oalts']="treAnltsRmo";}else{echo "Invalid password!";}}
    if(!isset($_SESSION['oalts'])){?>
    <div class="lgn_anlyts">
        <div class="lgn_anlts_bnr"><h2>Login To Analytics<h2></div>
        <form action="" method="post">
        <input type='password' name='pd' placeholder='Password'>
        <button type="submit">Submit</button>
        </form> 
    </div>
    <?php }else{?>
    <div style='display:flex;justify-content:center;'><div class="pgldr_dvbx" style='position:fixed;margin-left: 5px;z-index: 100;left: 0;margin-top: 18px;;z-index:100;display:none;'><div class="loadingio-spinner-ball-f98al3ulpa"><div class="ldio-xgt7432ktkl">
<div></div>
</div></div>
<style type="text/css">
@keyframes ldio-xgt7432ktkl {
  0%, 100% {
    animation-timing-function: cubic-bezier(0.45,0,0.9,0.55)
  }
  0% {
    transform: translate(0,0)
  }
  60% {
    transform: translate(0,48px);
    animation-timing-function: cubic-bezier(0,0.45,0.55,0.9);
  }
  100% {
    transform: translate(0,0);
  }
}

.ldio-xgt7432ktkl div {
  position: absolute;
  width: 32px;
  height: 32px;
  border-radius: 50%;
  background: #fab303;
  left: 34px;
  top: 10px;
  animation: ldio-xgt7432ktkl 1s linear infinite;
}
.loadingio-spinner-ball-f98al3ulpa {
  width: 60px;
  height: 60px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-xgt7432ktkl {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(0.6);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-xgt7432ktkl div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style></div><img src='../includes/fn_img/alarmclock.png' style='width:50px;height:50px;border-radius:100px;'><h1 style='margin-top:8px;margin-left:6px;'>Analytics</h1></div>
    <div class="shrt_nvgtn_dv_bx mnu_dsply_nvgtr">
        <div class="srt_nv_dsply"><a href='#top' class='hst_dsply_ttl'>Top</a></div>
        <div class="srt_nv_dsply"><a href='#users' class='hst_dsply_ttl'>Users</a></div>
        <div class="srt_nv_dsply"><a href='#stores' class='hst_dsply_ttl'>Stores</a></div>
        <div class="srt_nv_dsply"><a href='#orders' class='hst_dsply_ttl'>Orders</a></div>
        <div class="srt_nv_dsply"><div class='hst_dsply_ttl' id='pencil'>Pencil</div></div>
    </div>
    <div class="ddl_cnvs_dsply" id="sketch">
      <canvas
        class="ddl_cnvs"
        id="ddl_pad"
      ></canvas>
    </div>
    <div class="shrt_nvgtn_dv_bx ddl_clrs_dvbx">
        <div class="srt_nv_dsply"><div class='horiz'>=</div></div>
        <div class="srt_nv_dsply"><div class="ddl_clrs" data-clr='pink' style='background:pink;'></div></div>
        <div class="srt_nv_dsply"><div class="ddl_clrs" data-clr='green' style='background:green;'></div></div>
        <div class="srt_nv_dsply"><div class="ddl_clrs" data-clr='lavender' style='background:lavender;'></div></div>
        <div class="srt_nv_dsply"><div class="ddl_clrs" data-clr='orange' style='background:orange;'></div></div>
        <div class="srt_nv_dsply"><input type="color" id="get_ddl_clr"></div>
        <div class="srt_nv_dsply"><div class='ddl_btns' id='ddl_cler'>clear</div></div>
        <div class="srt_nv_dsply"><div class="ddl_btns" id="ddl_undo">Undo</div></div>
    </div>
    <div class="_anlts_opnd" id='top'>
    <div class="nw_sts_us_nm_dsply">
        <div class="t_big_nm_sts_dsply">
        <div class="T_nms_dsply">
            <div class="t_nms_htg">Stores:</div>
            <div class="t_nm_htg ttl_sts"></div>
        </div>
        <div class="T_nms_dsply">
            <div class="t_nms_htg">Users:</div>
            <div class="t_nm_htg ttl_usrs"></div>
        </div>
        </div>
        <div class="hgst_oth_sts_sml_dsply">
            <div class="hst_sts_dsply"><a href='#users' class='hst_dsply_ttl'>Users</a></div>
            <div class="hst_sts_dsply"><a href='#stores' class='hst_dsply_ttl'>Stores</a></div>
            <div class="hst_sts_dsply"><a href='#orders' class='hst_dsply_ttl'>Orders</a></div>
        </div>
    </div>
    <div class="anlts_bd_dvbx" id='users'>
        <div class="anl_cds_dsply">
            <div class="crd_tp_hdr">
                <div class='rght_dv_bx'>
                <div class="hdr_tp_cntdbx">Total New Users Signed up</div>
                <div class="hdr_btm_cntdbx"><span class='crd_ttl2_qst'>New Users Today: </span><span class='crd_ttl_rply crd_usr_tdy_nm'>0</span></div>
                </div>
                <div class='lft_dv_bx'>
                <div class="crd_hdr_btns">
                    <div class="blue_btns crd_yrbtn" data-yrs='urs'>Year</div>
                    <div class="blue_btns crd_mthsbtn" data-mhs='urs'>Month</div>
                    <div class="blue_btns crd_rstbtn" data-abtn='urs'>All</div>
                </div>
                <div class="crd_tm_fltr">
                <select class="crd_y_bx sl_uy_bx ud_slct">
                    <?php
                    for($i=2021;$i<=date("Y");$i++){
                        echo "<option>$i</option>";
                    }
                    ?>
                </select>
                <select class="crd_m_bx sl_um_bx ud_slct">
                    <option >Jan</option>
                    <option >Feb</option>
                    <option >Mar</option>
                    <option >Apr</option>
                    <option >May</option>
                    <option >Jun</option>
                    <option >Jul</option>
                    <option >Aug</option>
                    <option >Sep</option>
                    <option >Oct</option>
                    <option >Nov</option>
                    <option >Dec</option>
                </select>
                <select class="crd_d_bx sl_ud_bx ud_slct">
                    <?php
                    for($i=1;$i<=31;$i++){
                        echo "<option>$i</option>";
                    }
                    ?>
                </select>
                </div>
                </div>
            </div>
            <div class="anl_crd_bdy">
            <div class="crd_tbl_bln">
                    <div class="crd_tbl_hdr">
                        <div class="tbl_clms">Date</div>
                        <div class="tbl_clms">Users</div>
                    </div>
                    <div class="crd_tbl_bdy urs_crd_tbl_bdy">
                    </div>
                </div>
            </div>
        </div>
        <div class="anl_cds_dsply">
            <div class="anl_crd_bdy">
            <div class="cnvstpdv" id="donutchart_u" style="width: 500px;height: 330px;margin-left: -58px;overflow-y:hidden;height: 330px;"></div>
            </div>
        </div>
        <div class="anl_cds_dsply" style='grid-column:1/span 2;max-height:800px;'>
            <!-- <div class="crd_tp_hdr"></div> -->
            <div class="anl_crd_bdy">
            <div class="dta_vsultn_dsply">
            <div class="cnvstpdv" id="Line_chart_u" style="width: 100%;height: height:800px;"></div>
            </div>
            </div>
        </div>
        <div class="anl_cds_dsply" id='stores' style="grid-column:1;">
            <div class="crd_tp_hdr">
                <div class='rght_dv_bx'>
                <div class="hdr_tp_cntdbx">Total New Stores Created</div>
                <div class="hdr_btm_cntdbx"><span class='crd_ttl2_qst'>New Stores Today: </span><span class='crd_ttl_rply crd_str_tdy_nm'>0</span></div>
                </div>
                <div class='lft_dv_bx'>
                <div class="crd_hdr_btns">
                    <div class="blue_btns crd_yrbtn" data-yrs='srs'>Year</div>
                    <div class="blue_btns crd_mthsbtn" data-mhs='srs'>Month</div>
                    <div class="blue_btns crd_rstbtn" data-abtn='srs'>All</div>
                </div>
                <div class="crd_tm_fltr">
                <select class="crd_y_bx sl_sy_bx sd_slct">
                    <?php
                    for($i=2021;$i<=date("Y");$i++){
                        echo "<option>$i</option>";
                    }
                    ?>
                </select>
                <select class="crd_m_bx sl_sm_bx sd_slct">
                    <option >Jan</option>
                    <option >Feb</option>
                    <option >Mar</option>
                    <option >Apr</option>
                    <option >May</option>
                    <option >Jun</option>
                    <option >Jul</option>
                    <option >Aug</option>
                    <option >Sep</option>
                    <option >Oct</option>
                    <option >Nov</option>
                    <option >Dec</option>
                </select>
                <select class="crd_d_bx sl_sd_bx sd_slct">
                    <?php
                    for($i=1;$i<=31;$i++){
                        echo "<option>$i</option>";
                    }
                    ?>
                </select>
                </div>
                </div>
            </div>
            <div class="anl_crd_bdy">
                <div class="crd_tbl_bln">
                    <div class="crd_tbl_hdr">
                        <div class="tbl_clms">Date</div>
                        <div class="tbl_clms">Stores</div>
                        <div class="tbl_clms">Grocry</div>
                        <div class="tbl_clms">Book</div>
                        <div class="tbl_clms">Bakery</div>
                        <div class="tbl_clms">Marts</div>
                        <div class="tbl_clms">Stall</div>
                        <div class="tbl_clms">Meat</div>
                        <div class="tbl_clms">Restarunt</div>
                    </div>
                    <div class="crd_tbl_bdy str_dta_tbl_bdy">
                    </div>
                </div>
            </div>
        </div>
        <div class="anl_cds_dsply" style='grid-column:2;grid-row:3/span 1;max-height:800px;max-width:300px'>
            <div class="anl_crd_bdy">
            <div class="cnvstpdv" id="donutchart_stps" style="width: 500px;height: 330px;margin-left: -58px;overflow:hidden;height: 330px;"></div>
            </div>
        </div>
        <div class="anl_cds_dsply" style='grid-column:1/span 2;max-height:800px;'>
            <!-- <div class="crd_tp_hdr"></div> -->
            <div class="anl_crd_bdy">
            <div class="dta_vsultn_dsply">
            <div class="cnvstpdv" id="Line_chart_s" style="width: 100%;height: height:800px;"></div>
            </div>
            </div>
        </div>
        <div class="anl_cds_dsply" id='orders'>
            <div class="crd_tp_hdr">
                <div class='rght_dv_bx'>
                <div class="hdr_tp_cntdbx">Total Orders Per Day</div>
                <div class="hdr_btm_cntdbx"><span class='crd_ttl2_qst'>Orders Today: </span><span class='crd_ttl_rply crd_ods_tdy_nm'>0</span></div>
                </div>
                <div class='lft_dv_bx'>
                <div class="crd_hdr_btns">
                    <div class="blue_btns crd_yrbtn" data-yrs='ods'>Year</div>
                    <div class="blue_btns crd_mthsbtn" data-mhs='ods'>Month</div>
                    <div class="blue_btns crd_rstbtn" data-abtn='ods'>All</div>
                </div>
                <div class="crd_tm_fltr">
                <select class="crd_y_bx sl_oy_bx od_slct">
                    <?php
                    for($i=2021;$i<=date("Y");$i++){
                        echo "<option>$i</option>";
                    }
                    ?>
                </select>
                <select class="crd_m_bx sl_om_bx od_slct">
                    <option >Jan</option>
                    <option >Feb</option>
                    <option >Mar</option>
                    <option >Apr</option>
                    <option >May</option>
                    <option >Jun</option>
                    <option >Jul</option>
                    <option >Aug</option>
                    <option >Sep</option>
                    <option >Oct</option>
                    <option >Nov</option>
                    <option >Dec</option>
                </select>
                <select class="crd_d_bx sl_od_bx od_slct">
                    <?php
                    for($i=1;$i<=31;$i++){
                        echo "<option>$i</option>";
                    }
                    ?>
                </select>
                </div>
                </div>
            </div>
            <div class="anl_crd_bdy">
            <div class="crd_tbl_bln">
                    <div class="crd_tbl_hdr">
                        <div class="tbl_clms">Date</div>
                        <div class="tbl_clms">Orders</div>
                        <div class="tbl_clms">C.A.S</div>
                        <div class="tbl_clms">PPd</div>
                    </div>
                    <div class="crd_tbl_bdy ods_crd_tbl_bdy">
                    </div>
                </div>
            </div>
        </div>
        <div class="anl_cds_dsply" style='grid-column:2;grid-row:5/span 2;max-height:800px;max-width:300px'>
            <div class="anl_crd_bdy">
            <div class="cnvstpdv" id="donutchart_o" style="width: 500px;height: 330px;margin-left: -58px;overflow:hidden;height: 330px;"></div>
            <div class="cnvstpdv" id="donutchart_opmtcr" style="width: 500px;height: 330px;margin-left: -58px;overflow:hidden;height: 330px;"></div>
            </div>
        </div>
        <div class="anl_cds_dsply" style='max-height:800px;width: 653px;'>
            <div class="anl_crd_bdy">
            <div class="dta_vsultn_dsply">
            <div class="cnvstpdv" id="donutchart_ocp" style="width: 500px;height: 330px;margin-left: -58px;overflow:hidden;height: 330px;"></div>
            <div class="cnvstpdv" id="donutchart_opd" style="width: 500px;height: 330px;margin-left: -58px;overflow:hidden;height: 330px;"></div>
            </div>
            </div>
        </div>
        <div class="anl_cds_dsply" style='grid-column:1/span 2;max-height:800px;'>
            <div class="anl_crd_bdy">
            <div class="cnvstpdv" id="Line_chart_o" style="width: 100%;max-height: 800px;"></div>
            </div>
        </div>
        
    </div>
    </div>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.js'></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script src="analysr.js"></script>
    <?php }?>
</body>
</html>